kind: ConfigMap
metadata:
  name: my-config1
apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>A simple HTML document</title>
    </head>
    <body>
        <p>This is Deployment One!<p>
    </body>
    </html>
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-config2
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>A simple HTML document</title>
    </head>
    <body>
        <p>This is Deployment Two!<p>
    </body>
    </html>
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginxconf
data:
  nginx.conf: |
    # user nginx;
    worker_processes  1;
    pid /tmp/nginx.pid;
    events {
     worker_connections  10240;
    }
    http {
     include /etc/nginx/conf.d/*.conf;
     client_body_temp_path /tmp/client_temp;
     proxy_temp_path       /tmp/proxy_temp_path;
     fastcgi_temp_path     /tmp/fastcgi_temp;
     uwsgi_temp_path       /tmp/uwsgi_temp;
     scgi_temp_path        /tmp/scgi_temp;
     server {
       listen       8765;
       server_name  localhost;
       location / {
         root   /usr/share/nginx/html;
         index  index.html index.htm;
       }
    
       location /api/customer/ {
         proxy_pass http://localhost:8282/api/customer/;
       }
       location /api/vendor/ {
         proxy_pass http://localhost:8383/api/vendor/;
       }
    
       location /seznam {
         proxy_pass http://www.seznam.cz/;
       }
     }

    }
  


